"""What the application needs from the outside world, and nothing more.

One persistence port (Store) instead of a repository per table: the core opens a
read or write session and asks for exactly the records it works with. The adapter
owns SQL, transactions and the change log (every write is recorded there, so use
cases never have to remember to publish changes).
"""
from contextlib import AbstractContextManager
from typing import Protocol

from zellige.domain.artifacts import Artifact
from zellige.domain.models import Branch, Conversation, Item, Record, Run


class BlobStore(Protocol):
    def put(self, storage_key: str, content: bytes) -> None:
        """Persist bytes atomically at the key; repeated writes are safe."""
        ...


class Clock(Protocol):
    def __call__(self) -> int:
        """Return Unix time in microseconds."""
        ...


class Session(Protocol):
    """One consistent view of the store; in a write session, one atomic transaction."""

    # Reads
    def conversation(self, conversation_id: str, *, include_deleted: bool = False) -> Conversation | None: ...
    def conversations(self, archived: bool, query: str, limit: int, offset: int) -> list[Conversation]: ...
    def branch(self, conversation_id: str, branch_id: str) -> Branch | None: ...
    def branches(self, conversation_id: str) -> list[Branch]: ...
    def item(self, conversation_id: str, item_id: str) -> Item | None: ...
    def run(self, conversation_id: str, run_id: str) -> Run | None: ...
    def runs(self, conversation_id: str, limit: int) -> list[Run]: ...
    def profiles(self) -> list[Record]: ...
    def latest_context_version(self, context_pack_id: str) -> int: ...
    def changes(self, cursor: int, limit: int) -> list[Record]: ...

    # Writes; each one is also appended to the change log.
    def add_conversation(self, conversation: Conversation) -> None: ...
    def save_conversation(self, conversation: Conversation) -> None: ...
    def add_branch(self, branch: Branch) -> None: ...
    def move_head(self, branch: Branch, expected_head: str | None) -> bool:
        """Save the branch only if its head is still `expected_head`."""
        ...
    def add_item(self, item: Item, artifact_links: list[tuple[str, str, int]]) -> None: ...
    def add_profile(self, profile: Record, version: Record) -> None: ...
    def add_context_pack(self, pack: Record, version: Record) -> None: ...
    def add_context_version(self, version: Record) -> None: ...
    def add_run(self, run: Run) -> None: ...
    def save_artifact_if_absent(self, artifact: Artifact) -> Artifact:
        """Store metadata unless the digest exists; return the first stored record.
        Only a new record is logged, so duplicate uploads publish one change."""
        ...


class Store(Protocol):
    def read(self) -> AbstractContextManager[Session]: ...

    def write(self) -> AbstractContextManager[Session]:
        """An atomic, serialized write. Constraint failures, at any point including
        commit, raise PersistenceConflict; everything rolls back on any error."""
        ...

    def check(self) -> str:
        """Storage integrity status, "ok" when healthy."""
        ...
