import { execFileSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const repository = fileURLToPath(new URL("../../../", import.meta.url));
const output = new URL("../../src/api/generated/schema.ts", import.meta.url);
const python = process.env.ZELLIGE_PYTHON ?? fileURLToPath(new URL(
  process.platform === "win32" ? "../../../.venv/Scripts/python.exe" : "../../../.venv/bin/python",
  import.meta.url,
));
const check = process.argv.includes("--check");

let schema;
try {
  schema = JSON.parse(execFileSync(python, ["-m", "zellige.export_openapi"], {
    cwd: repository,
    encoding: "utf8",
    maxBuffer: 4 * 1024 * 1024,
  }));
} catch (error) {
  console.error("Cannot export the backend contract. Run uv sync --frozen, or set ZELLIGE_PYTHON to a provisioned Python executable.");
  console.error(error.message);
  process.exit(1);
}

// Pydantic defaults are optional inputs, including nullable defaults.
const ast = await openapiTS(schema, { defaultNonNullable: false });
const generated = "/**\n * Generated by openapi-typescript from zellige.server.create_app().\n * DO NOT EDIT. Regenerate with npm --prefix web run api:generate.\n */\n\n" + astToString(ast);

if (check) {
  let current;
  try {
    current = await readFile(output, "utf8");
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  if (current !== generated) {
    console.error("OpenAPI types are missing or stale. Run npm --prefix web run api:generate.");
    process.exitCode = 1;
  } else {
    console.log("OpenAPI types are up to date.");
  }
} else {
  await mkdir(new URL(".", output), { recursive: true });
  await writeFile(output, generated, "utf8");
  console.log("Generated src/api/generated/schema.ts.");
}
